title: maki's blogs
description: welcome~~
theme: just-the-docs
color_scheme: dark

url: https://maki3cat.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout


